- name: Hide vagrant user on login screen
  become: true
  community.general.ini_file:
    path: /var/lib/AccountsService/users/vagrant
    section: "User"
    option: "SystemAccount"
    value: "true"
    mode: "0600"
  notify: Restart gdm3
