- name: Install packages
  ansible.builtin.import_tasks: packages.yml
  tags: ubuntu_desktop_packages
- name: Disable guest user
  ansible.builtin.import_tasks: disable_guestuser.yml
  tags: ubuntu_desktop_disable_guestuser
- name: Disable autolock
  ansible.builtin.import_tasks: disable_autolock.yml
  tags: ubuntu_desktop_disable_autolock
- name: Configure launcher
  ansible.builtin.import_tasks: launcher.yml
  tags: ubuntu_desktop_launcher
- name: Configure autologin
  ansible.builtin.import_tasks: autologin.yml
  tags: ubuntu_desktop_autologin
- name: Configure chromium keyring
  ansible.builtin.import_tasks: chromium_keyring.yml
  tags: ubuntu_desktop_chromium_keyring

- name: Clean up to reduce disk usage
  ansible.builtin.include_tasks: cleanup.yml
  tags: ubuntu_desktop_cleanup
  when: clean is defined and clean

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
