- name: hide vagrant user on login screen
  become: true
  ini_file:
    path: /var/lib/AccountsService/users/vagrant
    section: "User"
    option: "SystemAccount"
    value: "true"
  notify: restart gdm3
