- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    become: true
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 600
    when: ansible_os_family == 'Debian'

  roles:
  - role: "marvel_nccr.ubuntu_desktop"
