- name: Converge
  hosts: all

  vars:
  - run_tests: true

  pre_tasks:
  - name: Update apt cache.
    become: true
    apt: update_cache=yes cache_valid_time=600
    when: ansible_os_family == 'Debian'

  roles:
  - role: "marvel-nccr.ubuntu_desktop"
